language: python
env:
  global:
    - DATABASE_URL='postgres://postgres@localhost/user_management'
    - TERM='xterm-256color'
  matrix:
    - TOX_ENV=py27-django111
    - TOX_ENV=py34-django111
    - TOX_ENV=py35-django111
    - TOX_ENV=py27-djangopre
    - TOX_ENV=py34-djangopre
    - TOX_ENV=py35-djangopre
matrix:
  fast_finish: true
  allow_failures:
    - env: TOX_ENV=py27-djangopre
    - env: TOX_ENV=py34-djangopre
    - env: TOX_ENV=py35-djangopre
services:
  - postgresql
addons:
  postgresql: "9.4"
install:
  - pip install -U pip
  - pip install tox==1.9.0 coveralls
before_script:
  - psql -c 'CREATE DATABASE user_management' -U postgres;
script:
  - tox -e $TOX_ENV
after_success:
  coveralls
notifications:
  email: false
